### ISSUE TITLE
base issue

### ISSUE THREAD

**Issue by philippdormann** [gymh/windows#1]
Hatte schon länger Pläne eine Gymherzo Windows App zu entwickeln, könnte ich dazu die Api's verwenden?

_Originally posted by @Missin-No in https://github.com/gymh/android/issues/9#issuecomment-870512788_

**Comment by philippdormann** [comment]
@Missin-No kannst hier gerne deine Pläne vorstellen und nach benötigten APIs etc. fragen.

Bitte nicht mehr offtopic in gymh/android posten. Danke.

**Comment by Missin-No** [comment]
Ich hatte die Bezeichnung wohl falsch gelesen, werde ein neues Repo aufmachen und darin Fortschritte einbinden, werde dich darinnen markieren

**Comment by philippdormann** [comment]
Cool, danke.
Du kannst auch gerne die Developer Role direkt hier in diesem Repo hier bekommen, wenn du möchtest 🤓

Mit Windows Development werde ich mich wenig auseinandersetzen.

**Comment by Missin-No** [comment]
> Cool, danke.
> Du kannst auch gerne die Developer Role direkt hier in diesem Repo hier bekommen, wenn du möchtest 🤓
> 
> Mit Windows Development werde ich mich wenig auseinandersetzen.

Vielen Dank! Dev Rolle wäre nett! Kein Priblem, dazu bin ja ich da!

**Comment by Missin-No** [comment]
Danke, werde mich gleich an die Arbeit machen!

**Comment by Missin-No** [comment]
Kann nicht in das Repo schreiben, sicher dass ich die erforderlichen Rechte besitze?

**Comment by Missin-No** [comment]
Oh, mein Fehler, habe meine E-Mails nicht gecheckt...
