### ISSUE TITLE
Pre-Beta Version ohne Passwort

### ISSUE THREAD

**Issue by Mic-R** [gymh/windows#11]
Hallo,
die erste Pre-Beta Version wird wohl zuerst ohne Passwortsicherung erscheinen und erst in der ersten offiziellen Beta wird eine richtige Passwortsicherung zu finden sein. Dies hat den Grund, dass das hashen und salten von Passwörtern witerhin Probleme und Bugs bereitet.

Die Pre-Beta wird nicht öffentlich sein und nur im kleinen Kreis getestet (maximum 15 Personen).

Hoffe das ist in Ordnung @philippdormann .

geplante Fertigstellung der Pre-Beta: 24 September 2021
Registrierungsbeginn: eine Woche nach Fertigstellung.
Download voraussichtlich über Microsoft Store

**Comment by Missin-No** [comment]
Dies ist nur Vorraussichtlich und kann sich auch jederzeit ändern, möglicherweise wird die Passwortsicherung noch erscheinen

**Comment by Missin-No** [comment]
Du scheinst unglücklich oder verwirrt darüber zu sein, hast du einen Verbesserungsvorschlag?

**Comment by nicolaiort** [comment]
Frei verteilbare Sachen ohne Passwort ist immer schwierig und die eigene Erfahrung sagt alles mit Auth möglichst am Anfang bauen - macht weniger Scherereien im Nachgang.
Da die "Pre-Beta" ja erst im September fertig sein soll, sollte es technisch doch eigentlich kein Problem sein, das mit dem Passwort zu implementieren, oder? :)

**Comment by Missin-No** [comment]
Ja, da hast du Recht @nicolaiort, wie bereits hier gesagt weiß ich nicht ob ich es schaffen werde mit der passwort-Implementierung, deshalb auch das strenge Limit (15 ausgewählte Personen) und ausschließliches herunterladen durch den Microsoft Store. Ich setze mir nur gerne Ziele, da diese mich dann antreiben und ich dadurch mich eher zuerst auf die Features konzentriere um dann mehr Zeit für das Passwort zu haben.

> Dies ist nur Vorraussichtlich und kann sich auch jederzeit ändern, möglicherweise wird die Passwortsicherung noch rechtzeitig erscheinen

**Comment by nicolaiort** [comment]
Anfänger sind immer Willkommen, seh unsere Kommentare immer als gut gemeinte Tips (Abgesehen von Sicherheitsanforderungen oder Regeln was das Gymnasium und dessen Daten angeht).

Du bekommst das bestimmt hin - wenn du damit wenig Erfahrung hast würde ich erstmal den Store für kleine Tests außen vor lassen. Du kannst das Programm ja lokal Builden und die Exe verteilen (Ich glaube im Code gesehen zu haben, dass du Visual Studio nutzt) - das ist etwas flexibler und man kann nicht ausersehen Sachen im Store auf public stellen ^^

Ich hab leider aktuell keine Zeit, sonst würde ich mir deinen Code auch mal genauer anschauen - wenn sich das ändert und du immernoch aktiv am Projekt arbeitest melde ich mich mal....

Und da du erwähnt hast, dass du mit Crypto Probleme hast:
* https://riptutorial.com/csharp/example/9345/sha512
* https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha512?view=net-5.0
* https://www.codegrepper.com/code-examples/csharp/c%23+sha512+salt

**Comment by Missin-No** [comment]
Vielen dank @nicolaiort ich würde in keinem Fall von dir verlangen deine Zeit für jemanden wie mich einfach herzugeben, Die Quellen scheinen hilfreich zu sein, das werde ich mir nochmal ansehen. Ja, ich nutze VS. Ich meinte bloß, dass jemand ja dann die EXE leaken kann, was sehr schlecht wäre und im Store gibt es eine Möglichkeit ein downloadlimit zu erstellen und programme auf "unlisted" zu stellen. Danke nochmal für die Tipps. Wenn du Zeit findest wäre er natürlich super wenn du mal drüber schaust, scheinst schon sehr erfahren! Muss aber natürlich nicht sein. Die App wird jetzt zunächst erstmal mein kleines Baby sein ^^
Ach und wenn ihr wissen wollt wer ich überhaupt bin, hier meine Mail-Adresse: michael.reimchen@pm.me

**Comment by Missin-No** [comment]
Vielen dank @nicolaiort ich würde in keinem Fall von dir verlangen deine Zeit für jemanden wie mich einfach herzugeben, Die Quellen scheinen hilfreich zu sein, das werde ich mir nochmal ansehen. Ja, ich nutze VS. Ich meinte bloß, dass jemand ja dann die EXE leaken kann, was sehr schlecht wäre und im Store gibt es eine Möglichkeit ein downloadlimit zu erstellen und programme auf "unlisted" zu stellen. Danke nochmal für die Tipps. Wenn du Zeit findest wäre es natürlich super wenn du mal drüber schaust, scheinst schon sehr erfahren! Muss aber natürlich nicht sein. Die App wird jetzt zunächst erstmal mein kleines Baby sein ^^

**Comment by Missin-No** [comment]
Zu meinem neuesten Verbesserungen: Ich habe noch nichts gepusht, was schulinterne Daten anzeigt, nur die Navigationsseiten

**Comment by philippdormann** [comment]
OK.

Du kannst gerne pre-releases erstellen mit deinen binaries (exe oder sonst was) - dann kann ich mir was vorstellen.
Am Besten auch mit Discussions pro pre-release.

**Comment by Missin-No** [comment]
Ok, stelle noch die letzten Dinge fertig und erstelle dann ein Release "ohne Features".
Man kann den Login screen leider noch skippen...

**Comment by Missin-No** [comment]
Ich glaube ch habe es geschafft den Login-Screen zu erstellen! Er ist zwar noch langsam und hat bugs, aber aus irgendeinem Grund geht es jetzt 😅

**Comment by Missin-No** [comment]
> Ich glaube ich habe es geschafft den Login-Screen zu erstellen! Er ist zwar noch langsam und hat massive Bugs, aber aus irgendeinem Grund geht es jetzt 😅

Ich hasse es, grad geht es noch, jetzt nicht mehr, unglaublich...

**Comment by Missin-No** [comment]
Hänge grad seid 2 Stunden fest, glaube ich beende meinen Tag für heute und pushe morgen eine (hoffentlich) funktionierende Version (hoffentlich) mit Passwort.

**Comment by Missin-No** [comment]
Aus einem Tag sind wohl zwei geworden... Ich habe grad extreme Probleme überhaupt die App zum starten zu kriegen ebenso beginnt mein Laptop jetzt Probleme zu haben... Schlimm... Ich  weis nicht, wie lang der Zustand hier noch anhalten wird... Tut mir leid...

**Comment by philippdormann** [comment]
Oh weh ^^
Kein Stress :) und viel Erfolg

**Comment by Missin-No** [comment]
Es geht wieder, nur habe ich jeglichen Fortschrittverloren, und dieser war noch nicht auf Github gepusht, werde jetzt noch letzte Versuche angehen, die Daten wiederherzustellen, aber der Release wird sich wohl ein wenig Verschieben, da ich Parallel noch angefangen habe an einem neuem Projekt zu Arbeiten

**Comment by Mic-R** [comment]
Ich konnte die Daten leider nicht wiederherstellen

**Comment by Mic-R** [comment]
Ihr stellt bei Odit.Services keine NVME-SSD's wieder her, oder? Weil ich auch noch weitere Daten verloren habe...

**Comment by nicolaiort** [comment]
> Ihr stellt bei Odit.Services keine NVME-SSD's wieder her, oder? Weil ich auch noch weitere Daten verloren habe...

Wir bieten verschiedene Dienstleistungen rund um Datenrettung an.
Schreib uns bei Interesse bitte eine Mail, GitHub ist schließlich für Development da und nicht zur Kundenkommunikation/Werbung :)

**Comment by Mic-R** [comment]
War nur eine kurze Frage nebenbei :)

**Comment by nicolaiort** [comment]
Wir sind trotzdem gerne unter info@odit.services für dich da :)

**Comment by Mic-R** [comment]
Das Problem hat sich geklärt, siehe E-Mails. :(

**Comment by Mic-R** [comment]
Sooooooooo... Nochmal zusammengefasst, was ich in den letzten zwei Tagen erledigt habe:


1.  Überdenken, wie zur Hölle ich das jetzt umsetze (Warum habe ich immer Ideen, die dir zu 100% nicht gefallen werden!?)

Ich habe in den beiden Tagen eher wenig gecodet, sondern nur übelegt. Ich habe mein altes Konzept jetzt erstmal hingeschmissen. Dafür hab ich jetzt ein neues (tut mir leid, wenn es dir nicht gefällt, es ist nur ein Vorschlag). 

2. Die Idee

Meine Idee war es, eine komplett neue Website zu erstellen. Die Einbindung in die Schulwebsite ist bisschen "kompliziert" über den PC zu erreichen. Hier würde meine Idee ins Spiel kommen (ein fertiges Grundprinzip besitze ich schon). 
(Die Domain könnte man zum Beispiel "Vertertungsplan-gymh.de" oder "vertretung-gymh.de" nennen [noch nicht geschaut ob die frei sind].
Kurze Seitenfrage: die Vertretungspläne sind auf deinen Domains doch Public einsehbar, warum muss dann das Passwort so gesichert sein?

3. Was ist jetzt das Konzept?

Inspiriert von deinen ganzen Repos auf Gymh, habe ich an einen Schulhub gedacht.
Dort sind alle Features aus der App und noch mehr verfügber (Synchro über Geräte als nächster Schritt? Kontoerstellung für Schüler? Passwort und Username der Website als Sicherheit?) .
Das ganze läuft dann nach meiner Vorstellung auf Apache und MySql.
Für die Websiten dann PHP.

4. Warum?

Vereinfachung für alle User, mehr Funktionsumfang.
Synchronisierung über  Geräte.
Uvm.
(Auch vielleicht, dass C# [in meinen Augen] EINFACH NUR SCHLIMM IST. [Außerdem hab ich das jetzt zwei Jahre lang nicht mehr genutzt und so ungefähr viel vergessen hab 😅)

5. Wie kommt das Geld dafür rein? 

Gute Frage, ich hab keine Ahnung, Werbung können wir ja schlecht einbinden. Spenden kommen sicher auch zu wenig rein. Geld von der Schule bekommen wir auch schlecht. Das ist wohl ne Sorge für später.


---
Tut mir leid wenn das jetzt bisschen unverständlich war, heut war ein langer Tag....

**Comment by Mic-R** [comment]
(Auf euch kommt fast keine Arbeit dann zu, PHP ist meine "Leidenschaft"

**Comment by Mic-R** [comment]
![image](https://user-images.githubusercontent.com/86645595/125818488-0dcefa8d-b12a-4750-bc52-93bc7a84a625.png)
![image](https://user-images.githubusercontent.com/86645595/125818545-cce78a9f-e02a-4fbd-9571-764cbbf1f75b.png)

**Comment by Mic-R** [comment]
> Sooooooooo... Nochmal zusammengefasst, was ich in den letzten zwei Tagen erledigt habe:
> 
> 1. Überdenken, wie zur Hölle ich das jetzt umsetze (Warum habe ich immer Ideen, die dir zu 100% nicht gefallen werden!?)
> 
> Ich habe in den beiden Tagen eher wenig gecodet, sondern nur übelegt. Ich habe mein altes Konzept jetzt erstmal hingeschmissen. Dafür hab ich jetzt ein neues (tut mir leid, wenn es dir nicht gefällt, es ist nur ein Vorschlag).
> 
> 1. Die Idee
> 
> Meine Idee war es, eine komplett neue Website zu erstellen. Der Vertretungsplan in der Schulwebsite ist bisschen "kompliziert" über den PC zu erreichen. Hier würde meine Idee ins Spiel kommen (ein fertiges Grundprinzip besitze ich schon).
> (Die Domain könnte man zum Beispiel "Vertertungsplan-gymh.de" oder "vertretung-gymh.de" nennen [noch nicht geschaut ob die frei sind].
> Kurze Seitenfrage: die Vertretungspläne sind auf deinen Domains doch Public einsehbar, warum muss dann das Passwort so gesichert sein?
> 
> 1. Was ist jetzt das Konzept?
> 
> Inspiriert von deinen ganzen Repos auf Gymh, habe ich an einen Schulhub gedacht.
> Dort sind alle Features aus der App und noch mehr verfügber (Synchro über Geräte als nächster Schritt? Kontoerstellung für Schüler? Passwort und Username der Website als Sicherheit?) .
> Das ganze läuft dann nach meiner Vorstellung auf Apache und MySql.
> Für die Websiten dann PHP.
> 
> 1. Warum?
> 
> Vereinfachung für alle User, mehr Funktionsumfang.
> Synchronisierung über Geräte.
> Uvm.
> (Auch vielleicht, dass C# [in meinen Augen] EINFACH NUR SCHLIMM IST. [Außerdem hab ich das jetzt zwei Jahre lang nicht mehr genutzt und so ungefähr viel vergessen hab 😅)
> 
> 1. Wie kommt das Geld dafür rein?
> 
> Gute Frage, ich hab keine Ahnung, Werbung können wir ja schlecht einbinden. Spenden kommen sicher auch zu wenig rein. Geld von der Schule bekommen wir auch schlecht. Das ist wohl ne Sorge für später.
> 
> Tut mir leid wenn das jetzt bisschen unverständlich war, heut war ein langer Tag....

Sorry, die Nachricht habe ich komplett in du geschrieben, natürlich seid ihr beide gemeint

**Comment by Mic-R** [comment]
Sehe grad, dass mein Kommentar gelöscht wurde, natürlich war der Kommentar nicht unhöflich gemeint ^^

**Comment by philippdormann** [comment]
> Sehe grad, dass mein Kommentar gelöscht wurde, natürlich war der Kommentar nicht unhöflich gemeint ^^

war zum Aufräumen, Antworten kommen gleich :)

**Comment by nicolaiort** [comment]
Also ganz grundsätzlich erstmal: Mach im rechtlichen Rahmen worauf du bock hast.

Neue Domain für Vertretungsplan: Nicht wirklich nutzerfreundlich - der Ottonormalverbraucher erwartet die Infos nunmal auf der Seite der Schule und 3 Klicks zum Vertretungsplan des heutigen Tages ist jetzt auch nicht zuuuu viel verlangt.

VP "öffentlich" erreichbar: Technisch gesehen ist die Website des GymH auch öffentlich. Nutzername+Passwort ist hier eine verpflichtende Schwelle und kein Hochsicherheitsbereich - versuch gerne mal das der Schule zu erklären ^^

Dein Schulhub: Es gibt eine GymH App, wenn du da Ideen für Erweiterungen hast können die gerne dahin - Kein Plan, was du mit Sync über Devices willst).
Extra User für Schüler halte ich für aufwändig und macht auch wieder mit Datenschutz ganz viel Spaß. 
Mit meiner Meinung zum "Techstack" PHP/Apache/MySQL fang ich erst gar nicht an - aber jedem das seine...

Finanzierung sollte bei Projekten für die Schule nicht das Ziel sein (die Apps von Philipp sind z.B. als Seminararbeit und in der Freizeit aus Spaß entstanden).

**Comment by Mic-R** [comment]
> Also ganz grundsätzlich erstmal: Mach im rechtlichen Rahmen worauf du bock hast.
> 
> Neue Domain für Vertretungsplan: Nicht wirklich nutzerfreundlich - der Ottonormalverbraucher erwartet die Infos nunmal auf der Seite der Schule und 3 Klicks zum Vertretungsplan des heutigen Tages ist jetzt auch nicht zuuuu viel verlangt.
> 
> VP "öffentlich" erreichbar: Technisch gesehen ist die Website des GymH auch öffentlich. Nutzername+Passwort ist hier eine verpflichtende Schwelle und kein Hochsicherheitsbereich - versuch gerne mal das der Schule zu erklären ^^
> 
> Dein Schulhub: Es gibt eine GymH App, wenn du da Ideen für Erweiterungen hast können die gerne dahin - Kein Plan, was du mit Sync über Devices willst).
> Extra User für Schüler halte ich für aufwändig und macht auch wieder mit Datenschutz ganz viel Spaß. 
> Mit meiner Meinung zum "Techstack" PHP/Apache/MySQL fang ich erst gar nicht an - aber jedem das seine...
> 
> Finanzierung sollte bei Projekten für die Schule nicht das Ziel sein (die Apps von Philipp sind z.B. als Seminararbeit und in der Freizeit aus Spaß entstanden).

OK, ich glaube ich hab mich falsch ausgedrückt.
Sync über Geräte war für zb den Stundenplan oder Notizen/To-do gemeint.
Konten für Schüler sind meiner Meinung nach nicht ganz so schwer....
Warum ich frage: Phillip hat sich schon länger damit befasst, von dir weiß ich leider noch ganz so viel...
Deshalb habe ich nur hier um ein gut schlecht beten wollen.
Außerdem habe ich keine eigene Server-Infrastruktur...

**Comment by philippdormann** [comment]
Das, was @nicolaiort schon gesagt hat:
> Mach im rechtlichen Rahmen worauf du bock hast.

> Vereinfachung für alle User, mehr Funktionsumfang.

- was ist aktuell nicht einfach
- welche Funktionen denn noch??

> Uvm.

was ist denn das **mehr**?

**Nebenbei**: Typo in deinen Domains 👀

**Comment by Mic-R** [comment]
> Das, was @nicolaiort schon gesagt hat:
> > Mach im rechtlichen Rahmen worauf du bock hast.
> 
> > Vereinfachung für alle User, mehr Funktionsumfang.
> 
> - was ist aktuell nicht einfach
> - welche Funktionen denn noch??
> 
> > Uvm.
> 
> was ist denn das **mehr**?
> 
> **Nebenbei**: Typo in deinen Domains 👀

Mehr wäre zum Beispiel der Geräte-Sync und ein Kalender. (nur Beispiele, ich habe mich jetzt nicht festgelegt, um zu sehen, was ich da denn nutzen kann)

**Comment by philippdormann** [comment]
**Konten**
- technisch ist das natürlich nicht schwer
1. wird das keiner nutzen + sich registrieren
2. musst du das dann datenschutzrechtlich absichern, Verträge mit der Schule etc.

**Sync TODO/ Stundenplan**
Geb ich dir nur unter Umständen recht

**Comment by nicolaiort** [comment]
> Sync TODO/ Stundenplan

Ich meine Sync ist immer nett, aber ich kenne niemanden, der mehrere Devices für den VP nutzt - an sich nicht schlecht, hängen aber wieder Accounts oder so dran

**Comment by Mic-R** [comment]
> **Konten**
> - technisch ist das natürlich nicht schwer
> 1. wird das keiner nutzen + sich registrieren
> 2. musst du das dann datenschutzrechtlich absichern, Verträge mit der Schule etc.
> 
> **Sync TODO/ Stundenplan**
> Geb ich dir nur unter Umständen recht

OOF, OK, die Idee ist glaub ich weg, zurück zum alten Konzept

**Comment by philippdormann** [comment]
> **Sync TODO/ Stundenplan**

siehe auch https://github.com/gymh/ios/issues/13

**Comment by Mic-R** [comment]
> **Konten**
> - technisch ist das natürlich nicht schwer
> 1. wird das keiner nutzen + sich registrieren
> 2. musst du das dann datenschutzrechtlich absichern, Verträge mit der Schule etc.
> 
> **Sync TODO/ Stundenplan**
> Geb ich dir nur unter Umständen recht

Zu, dass das niemand nutzen wird, warum denn? Direkte Verlinkung über die Homepage usw...

**Comment by nicolaiort** [comment]
Homepage Account Management != App Account Management

**Comment by Mic-R** [comment]
> Homepage Account Management != App Account Management

Wir gesagt, zurück zum alten Konzept, vielleicht landet das "neue" Konzept in meiner Privaten Bastelkiste

**Comment by Mic-R** [comment]
> > Homepage Account Management != App Account Management
> 
> Wir gesagt, zurück zum alten Konzept, vielleicht landet das "neue" Konzept in meiner Privaten Bastelkiste

Das hätte ich nur vorgestellt hauptsächlich, da ich mich mit PHP um längen mehr auskenne als in C#, dass ich seit 2 Jahren nicht genutzt habe.

**Comment by nicolaiort** [comment]
Das wird langsam alles zu offtopic - mach zu deinen App Ideen gerne eine Discussion auf.

**Comment by Mic-R** [comment]
OK, das sind jetzt viele Kommis von mir, tut mir leid.

Ich denke, ich werde mir das Leben jetzt einfach machen und das PHP Zeugs schreiben (lokales ablegen der Daten die der User eingibt) und mache dann einfach ein Webview in eiener UWP. Ja, es ist ein wenig "nicht wundervoll gelöst" aber, ich denke so wäre es für mich einfacher und ihr müsst nicht so oft zur Hilfe kommen, wenn ich mit C# mal wieder Probleme habe.

**Comment by Mic-R** [comment]
> Das wird langsam alles zu offtopic - mach zu deinen App Ideen gerne eine Discussion auf.
> 
> Für Organisatorische Sachen git es dieses Repo: https://github.com/gymh/org/

OK (Wenn man lang mit mir arbeitet, sieht man oft, dass ich immer alles zusammenpacke und dann erst ordne ^^)
