### ISSUE TITLE
Cookies werden ohne Erlaubniss abgelegt - rechtliche Situation

### ISSUE THREAD

**Issue by Missin-No** [gymh/windows#12]
Cookies werden ohne Erlaubniss im Browser abgelegt, soweit ich das sehen konnte.

Dies ist bei den Funktionen:

ToDo
Stundenplan

der Fall.

Hier wollte ich mich wegen der rechtlichen Situation nochmal erkundigen. @philippdormann 
Sollten gar keine Cookies abgelegt werden, tut es mir leid, vielleicht habe ich es falsch ausgewertet...

Auszug aus [Ionos](https://www.ionos.de/digitalguide/websites/online-recht/cookie-richtlinie/):

"Die von der Beklagten in Form einer Allgemeinen Geschäftsbedingung vorgesehene Einwilligung des Nutzers, die den Abruf von auf seinem Endgerät gespeicherten Informationen mithilfe von Cookies im Wege eines voreingestellten Ankreuzkästchens gestattet, stellt sowohl nach dem im Zeitpunkt der beanstandeten Handlung geltenden Recht als auch nach dem im Entscheidungszeitpunkt geltenden Recht eine unangemessene Benachteiligung des Nutzers dar." – Bundesgerichtshof.

---

**Comment by philippdormann** [comment]
Hi Michi,

wie genau kommst du darauf, dass auf den Seiten /stundenplan/ und /todo/ Cookies gesetzt werden?
Wäre mir neu 😄😄

**Comment by Missin-No** [comment]
Soweit ich weiß bin ich dumm und als ich grad nachgeschaut hab, hat sich das bestätigt, ich habe mein Cookie Prüftool nicht zurückgesetzt und dann noch welche von Google, Facebook und anderen Diensten Gesehen.... Mein Fehler, tut mir leid....

Ich hatte das Tool nur genutzt um zu wissen wie ich das WebView Element konfigurieren muss...

**Comment by philippdormann** [comment]
Kein Problem :)
