### ISSUE TITLE
Designvorlage

### ISSUE THREAD

**Issue by Missin-No** [gymh/windows#4]
@philippdormann Besitzt du eine Designvorlage für das Userinterface?

**Comment by philippdormann** [comment]
Nein, sowas haben wir nicht :)

Auf jeden Fall eine saubere Font wie Roboto/ Inter

Oder wenn du eine UWP baust eben Windows-native Design 😉

Nach Möglichkeit auch immer einen Darkmode sowie grundlegend WCAG 2.0 Color Contrast 👍

**Comment by Missin-No** [comment]
Ok, wollte bloß fragen, damit alles dann sauber läuft, danke!

**Comment by Missin-No** [comment]
Ach und wenn du gleich da bist, kontaktiere mich bitte kurz unter michael.reimchen@protonmail.com
