### ISSUE TITLE
Sicherheit

### ISSUE THREAD

**Issue by Missin-No** [gymh/windows#6]
@philippdormann Wird eine starke Sicherung der Daten benötigt oder reicht eine einfache?

**Comment by philippdormann** [comment]
Was genau meinst du denn mit "starke Sicherung"? 🧐🤷‍♂️

**Comment by Missin-No** [comment]
Zum Beispiel darf ich das Passwort in den Code schreiben oder muss ich es vom Server abfragen?

**Comment by philippdormann** [comment]
Achso 😀
Nach Möglichkeit bitte Benutzername + Passwort mindestens als sha512 hash in-app

**Comment by Missin-No** [comment]
Siehe anderes Issue
