### ISSUE TITLE
Url is invalid

### ISSUE THREAD

**Issue by Missin-No** [gymh/windows#9]
Hallo @philippdormann,
könntest du auf deiner Domain Url-Weiterleitungen für diese Links erstellen und diese Möglichst kurz und ohne sonderzeichen halten?

Links:
https://gymh.philippdormann.de/vertretungsplan/?f=&display-lehrer-full&d=mo
https://gymh.philippdormann.de/vertretungsplan/?f=&display-lehrer-full&d=di
https://gymh.philippdormann.de/vertretungsplan/?f=&display-lehrer-full&d=mi
https://gymh.philippdormann.de/vertretungsplan/?f=&display-lehrer-full&d=do
https://gymh.philippdormann.de/vertretungsplan/?f=&display-lehrer-full&d=fr

Danke!
Das Problem ist, dass VS ein & als Zeichen für eine Sequenz erkennt und ich nicht unbedingt das noch reinhauen möchte und es so viel einfacher wäre wenn du die weiterleitunge erstellst.

**Comment by Missin-No** [comment]
Wenn ja, übermittle mir bitte die Links

**Comment by nicolaiort** [comment]
Ist unnötig, C# kann mit Sonderzeichen umgehen zumal die aktuellen URLs den entsprechenden Standards entsprechen (sind ja query Parameter)
Wenn du (warum auch immer) in Strings Probleme mit '&' hast -> Einfach escapen.

**Comment by Missin-No** [comment]
> Ist unnötig, C# kann mit Sonderzeichen umgehen zumal die aktuellen URLs den entsprechenden Standards entsprechen (sind ja query Parameter)
> Wenn du (warum auch immer) in Strings Probleme mit '&' hast -> Einfach escapen.

Genau das habe ich auch probiert nur werden Fehler weiterhin ausgespuckt..

**Comment by Missin-No** [comment]
Schaue morgen nochmal genauer drauf, bin zurzeit nicht in der Nähe meines Laptops

**Comment by Missin-No** [comment]
> Ist unnötig, C# kann mit Sonderzeichen umgehen zumal die aktuellen URLs den entsprechenden Standards entsprechen (sind ja query Parameter)
> Wenn du (warum auch immer) in Strings Probleme mit '&' hast -> Einfach escapen.

Du scheinst dich mit C# auszukennen, weißt du zufällig auch wie das nochmal mit gehachten login-Forms war, hab lange nicht mehr mit solchen gearbeitet

**Comment by Missin-No** [comment]
Hab es jetzt umgeschrieben @nicolaiort 
` <WebView x:Name="Webview" Source="https://gymh.philippdormann.de/vertretungsplan/?f=\x38display-lehrer-full\x38d=mo" HorizontalAlignment="Left" Height="716" Margin="162,165,0,0" VerticalAlignment="Top" Width="1601"/>`
Jetzt zeigt es mir aber den plan für heute an mit dem falsche Filter...

**Comment by Missin-No** [comment]
Tut mir leid, habe grad den Fehler entdeckt
Ich sage selbst ich bin grad xaml und escape auf dem C# weg...
&amp ist der Weg für Xaml...
